# updated dvc.yaml

stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/external
    - data/raw

  data_validation:
    cmd: python src/data/data_validation.py
    deps:
    - src/data/data_validation.py
    outs:
    - data/report

  data_transformation:
    cmd: python src/data/data_transformation.py
    deps:
    - src/data/data_transformation.py
    outs:
    - data/processed
    
  model_building:
    cmd: python src/model/model_trainer.py
    deps:
    - src/model/model_trainer.py
    outs:
    - reports
    
  model_registering:
    cmd: python src/model/register_model.py
    deps:
    - src/model/register_model.py
    

